version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootwordpress
    ports:
      - 3306:3306

  wordpress:
    container_name: 'wordpress-local'
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 5000:80
    environment:
      MYSQL_HOST: db:3306
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootwordpress
    volumes:
      - ./wordpress:/var/www/html

volumes:
  db_data: {}