version: '3.8'

services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    volumes:
      - ./app:/var/www/html
    ports:
      - 5000:80
    networks:
      - servidor-web
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: servidor-mysql
    environment:
      MYSQL_DATABASE: phpdoctrine
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - 6000:3306
    networks:
      - servidor-web
    restart: always

networks:
  servidor-web:
